on:
  workflow_call:
    inputs:
      CODE_REPO:
        description: 'repository name'
        required: true
        type: string
    secrets:
      REGISTRY_URL:
        description: 'Registry URL to pull the docker images from'
        required: false
      ECR_URL:
        description: 'ECR URL to push the docker image to'
        required: false
      AWS_ROLE_ARN:
        description: 'ARN of the AWS Role to assume when pushing to ECR'
        required: false
      AWS_REGION:
        description: 'The default AWS Region'
        required: false

jobs:
  maven-build:
    runs-on: ubuntu-latest  

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.CODE_REPO }}

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  
          distribution: 'temurin' 

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true  

      - name: Run tests with Maven
        run: mvn test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: the-jar-file
          path: target/*.jar  # Adjust the path to where your JAR file is located