on:
  workflow_call:
    inputs:
      CODE_REPO:
        description: 'repository name'
        required: true
        type: string
    secrets:
      REGISTRY_URL:
        description: 'Registry URL to pull the docker images from'
        required: false
      ECR_URL:
        description: 'ECR URL to push the docker image to'
        required: false
      AWS_ROLE_ARN:
        description: 'ARN of the AWS Role to assume when pushing to ECR'
        required: false
      AWS_REGION:
        description: 'The default AWS Region'
        required: false

jobs:
   docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.CODE_REPO }}

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: the-jar-file
      - name: Display structure of downloaded files
        run: ls -R

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t webapp .
        
      - name: Push Docker image (optional)
        run: |
          docker tag webapp my-repository/webapp:latest
          docker push my-repository/webapp:latest